apiVersion: v1
kind: service
metadata:
  name: react-gke-service
  namespace: react-gke
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: react-gke
  type: NodePort